# Generated by Django 5.1.1 on 2024-10-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnythb',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
