# Generated by Django 5.1.1 on 2025-02-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_cnythb_date_alter_usdthb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdthb',
            name='diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
