# Generated by Django 5.1.1 on 2025-03-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USDTHB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_time', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=16, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
