# Generated by Django 5.1.1 on 2025-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usdthb',
            name='created_time',
        ),
    ]
