# Generated by Django 5.1.1 on 2025-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_usdthb_created_at_remove_usdthb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdthb',
            name='created_at',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usdthb',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
