# Generated by Django 5.1.1 on 2025-03-26 21:09

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_usdthb_created_at_usdthb_date_alter_usdthb_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=data.models.current_timestamp)),
                ('price', models.FloatField(blank=True, null=True)),
                ('bar_sell_price', models.FloatField(default=0.0)),
                ('bar_price_change', models.FloatField(default=0.0)),
                ('ornament_buy_price', models.FloatField(default=0.0)),
                ('ornament_sell_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField()),
                ('created_time', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='created_at',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='date',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='usdthb',
            name='timestamp',
            field=models.IntegerField(default=data.models.current_timestamp),
        ),
    ]
