# Generated by Django 5.1.1 on 2025-03-28 01:11

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_goldth_alter_usdthb_created_at_alter_usdthb_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=data.models.current_timestamp)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('close_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('low_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume_weight_avg', models.FloatField(blank=True, default=0.0, null=True)),
                ('num_transactions', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='goldth',
            name='bar_price_change',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='goldth',
            name='bar_sell_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='goldth',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='goldth',
            name='ornament_buy_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='goldth',
            name='ornament_sell_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='goldth',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
