# Generated by Django 5.1.1 on 2024-09-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gold_US', '0002_goldpricexau_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='ch',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='chp',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='prev_close_price',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_10k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_14k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_16k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_18k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_20k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_21k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_22k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='price_gram_24k',
        ),
        migrations.RemoveField(
            model_name='goldpricexau_api',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='high',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='low',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='open',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='percent',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='unitTHB',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='unitUSD',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='goldpricexau_api',
            name='volume',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goldpricexau_api',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goldpricexau_api',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
