# Generated by Django 5.1.1 on 2025-02-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(null=True, unique=True)),
                ('price_0', models.FloatField(null=True)),
                ('price_1', models.FloatField(null=True)),
                ('price_2', models.FloatField(null=True)),
                ('price_3', models.FloatField(null=True)),
                ('price_4', models.FloatField(null=True)),
                ('price_5', models.FloatField(null=True)),
                ('price_6', models.FloatField(null=True)),
                ('price_7', models.FloatField(null=True)),
                ('date', models.CharField(max_length=16, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
