# Generated by Django 5.1.1 on 2025-03-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_predict',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
