# Generated by Django 5.2 on 2025-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predicts", "0003_month_month_predict"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="date_1",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_2",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_3",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_4",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_5",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_6",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="date_7",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
