# Generated by Django 5.2 on 2025-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predicts", "0004_week_date_1_week_date_2_week_date_3_week_date_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="month",
            name="price_high",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="month",
            name="price_low",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="month",
            name="price_open",
            field=models.FloatField(null=True),
        ),
    ]
