# Generated by Django 5.1.1 on 2024-09-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('repeat', models.BooleanField()),
            ],
            options={
                'db_table': 'background_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyGoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('gold_price', models.FloatField()),
            ],
        ),
    ]
