# Generated by Django 5.1.1 on 2025-02-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0002_alter_gold_cny_diff_alter_gold_cny_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_thb',
            name='diff',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gold_thb',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gold_thb',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gold_thb',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gold_thb',
            name='percent',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gold_thb',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
