# Generated by Django 5.1.1 on 2024-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPriceUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('open', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, default='0', max_digits=15)),
                ('percent', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('unitUSD', models.CharField(default='0', max_length=10)),
                ('unitTHB', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
