# Generated by Django 5.1.1 on 2024-12-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_time', models.CharField(blank=True, max_length=10, null=True)),
                ('bar_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bar_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bar_price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ornament_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ornament_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('created_date_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
