# Generated by Django 5.1.1 on 2025-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_time', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bar_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bar_price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ornament_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ornament_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gold_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_weight_avg', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=15, null=True)),
                ('num_transactions', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
