# Generated by Django 5.1.1 on 2025-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_us',
            name='timestamp',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
