# Generated by Django 5.1.1 on 2025-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0002_alter_gold_us_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_us',
            name='close_price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='high_price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='low_price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume_weight_avg',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
