# Generated by Django 5.1.1 on 2025-02-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0002_gold_th'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_th',
            old_name='bar_buy_price',
            new_name='price',
        ),
    ]
