# Generated by Django 5.1.1 on 2025-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0003_alter_gold_us_close_price_alter_gold_us_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_us',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='high_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume_weight_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
