# Generated by Django 5.1.1 on 2025-02-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0003_rename_bar_buy_price_gold_th_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_th',
            old_name='created_date_time',
            new_name='date',
        ),
    ]
