# Generated by Django 5.1.1 on 2025-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0004_alter_gold_us_close_price_alter_gold_us_high_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_th',
            name='date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_th',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
