# Generated by Django 5.1.1 on 2025-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0004_rename_created_date_time_gold_th_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_th',
            name='date',
            field=models.CharField(max_length=10, blank=True, null=True),
        )
    ]
