# Generated by Django 5.1.1 on 2025-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0005_alter_gold_th_date_alter_gold_th_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_us',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='close_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='date',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='high_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='low_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='num_transactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='timestamp',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_us',
            name='volume_weight_avg',
            field=models.FloatField(null=True),
        ),
    ]
