# Generated by Django 5.1.1 on 2025-02-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0006_gold_us_created_at_alter_gold_us_close_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(null=True, unique=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
            ],
        ),
    ]
