# Generated by Django 5.1.1 on 2025-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnomenaGold', '0007_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='close',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='high',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='low',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open',
        ),
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
